/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/TZzGb4KaTQK
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Arimo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import {
  Pagination,
  PaginationContent,
  PaginationItem,
  PaginationPrevious,
  PaginationLink,
  PaginationEllipsis,
  PaginationNext,
} from "@/components/ui/pagination";

export function aaaa() {
  return (
    <div className="w-full max-w-3xl mx-auto px-4 md:px-6 py-12 md:py-20">
      <div className="space-y-6 text-center">
        <h1 className="text-3xl md:text-4xl font-bold">
          Bienvenido a nuestra plataforma
        </h1>
        <p className="text-muted-foreground text-lg md:text-xl">
          Estamos emocionados de que te hayas unido a nosotros. Completa tu
          perfil para empezar a disfrutar de todas las funcionalidades.
        </p>
      </div>
      <div className="mt-10 bg-background rounded-lg shadow-lg p-6 md:p-8">
        <form className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <Label htmlFor="name">Nombre</Label>
              <Input id="name" placeholder="Ingresa tu nombre" required />
            </div>
            <div>
              <Label htmlFor="email">Correo electrónico</Label>
              <Input
                id="email"
                type="email"
                placeholder="Ingresa tu correo electrónico"
                required
              />
            </div>
          </div>
          <div>
            <Label htmlFor="profile-picture">Foto de perfil</Label>
            <Input id="profile-picture" type="file" accept="image/*" />
          </div>
          <Button type="submit" className="w-full">
            Completar perfil
          </Button>
        </form>
      </div>
      <div className="mt-10">
        <Pagination>
          <PaginationContent>
            <PaginationItem>
              <PaginationPrevious href="#" />
            </PaginationItem>
            <PaginationItem>
              <PaginationLink href="#">1</PaginationLink>
            </PaginationItem>
            <PaginationItem>
              <PaginationLink href="#" isActive>
                2
              </PaginationLink>
            </PaginationItem>
            <PaginationItem>
              <PaginationLink href="#">3</PaginationLink>
            </PaginationItem>
            <PaginationItem>
              <PaginationEllipsis />
            </PaginationItem>
            <PaginationItem>
              <PaginationNext href="#" />
            </PaginationItem>
          </PaginationContent>
        </Pagination>
      </div>
    </div>
  );
}
