/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/S5TeAMQJbV3
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Arimo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Busqueda() {
  return (
    (<div className="bg-background text-foreground">
      <header
        className="sticky top-0 z-40 w-full border-b bg-background/80 backdrop-blur-sm">
        <div
          className="container mx-auto flex h-16 max-w-6xl items-center justify-between px-4 sm:px-6 lg:px-8">
          <Link href="#" className="flex items-center gap-2 font-bold" prefetch={false}>
            <ShoppingBagIcon className="h-6 w-6" />
            <span>Acme Store</span>
          </Link>
          <div className="relative flex-1 max-w-md">
            <Input
              type="search"
              placeholder="Search products..."
              className="w-full rounded-full bg-muted px-4 py-2 pr-10 text-sm focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2" />
            <div className="absolute inset-y-0 right-2 flex items-center">
              <Button size="icon" variant="ghost">
                <SearchIcon className="h-5 w-5 text-muted-foreground" />
              </Button>
            </div>
          </div>
          <div className="hidden items-center gap-4 md:flex">
            <Link
              href="#"
              className="text-sm font-medium hover:text-primary"
              prefetch={false}>
              Categories
            </Link>
            <Link
              href="#"
              className="text-sm font-medium hover:text-primary"
              prefetch={false}>
              New Arrivals
            </Link>
            <Link
              href="#"
              className="text-sm font-medium hover:text-primary"
              prefetch={false}>
              Sale
            </Link>
            <Button>
              <ShoppingCartIcon className="h-5 w-5 mr-2" />
              Cart
            </Button>
          </div>
          <div className="md:hidden">
            <Button size="icon" variant="ghost">
              <MenuIcon className="h-6 w-6" />
            </Button>
          </div>
        </div>
      </header>
      <main className="container mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8">
        <div className="grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-3">
          <div className="col-span-1 md:col-span-2 lg:col-span-1">
            <h2 className="mb-4 text-2xl font-bold">Categories</h2>
            <div className="grid grid-cols-2 gap-4">
              <Link
                href="#"
                className="flex items-center justify-between rounded-lg bg-muted p-4 hover:bg-muted/80"
                prefetch={false}>
                <span className="text-sm font-medium">Clothing</span>
                <ChevronRightIcon className="h-5 w-5 text-muted-foreground" />
              </Link>
              <Link
                href="#"
                className="flex items-center justify-between rounded-lg bg-muted p-4 hover:bg-muted/80"
                prefetch={false}>
                <span className="text-sm font-medium">Electronics</span>
                <ChevronRightIcon className="h-5 w-5 text-muted-foreground" />
              </Link>
              <Link
                href="#"
                className="flex items-center justify-between rounded-lg bg-muted p-4 hover:bg-muted/80"
                prefetch={false}>
                <span className="text-sm font-medium">Home &amp; Garden</span>
                <ChevronRightIcon className="h-5 w-5 text-muted-foreground" />
              </Link>
              <Link
                href="#"
                className="flex items-center justify-between rounded-lg bg-muted p-4 hover:bg-muted/80"
                prefetch={false}>
                <span className="text-sm font-medium">Beauty</span>
                <ChevronRightIcon className="h-5 w-5 text-muted-foreground" />
              </Link>
            </div>
          </div>
          <div className="col-span-1 md:col-span-2 lg:col-span-2">
            <h2 className="mb-4 text-2xl font-bold">Popular Products</h2>
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
              <div className="rounded-lg bg-muted p-4 shadow-sm">
                <Link href="#" className="group" prefetch={false}>
                  <img
                    src="/placeholder.svg"
                    alt="Product Image"
                    width={300}
                    height={300}
                    className="mb-4 h-48 w-full rounded-lg object-cover transition-opacity group-hover:opacity-80"
                    style={{ aspectRatio: "300/300", objectFit: "cover" }} />
                  <h3 className="mb-2 text-lg font-medium">Product Name</h3>
                  <p className="text-muted-foreground">$49.99</p>
                </Link>
              </div>
              <div className="rounded-lg bg-muted p-4 shadow-sm">
                <Link href="#" className="group" prefetch={false}>
                  <img
                    src="/placeholder.svg"
                    alt="Product Image"
                    width={300}
                    height={300}
                    className="mb-4 h-48 w-full rounded-lg object-cover transition-opacity group-hover:opacity-80"
                    style={{ aspectRatio: "300/300", objectFit: "cover" }} />
                  <h3 className="mb-2 text-lg font-medium">Product Name</h3>
                  <p className="flex items-center justify-between">
                    <span className="flex items-center gap-4">
                      <img
                        src="/placeholder.svg"
                        alt="Product Image"
                        width={64}
                        height={64}
                        className="rounded-full"
                        style={{ aspectRatio: "64/64", objectFit: "cover" }} />
                      <span className="text-lg font-medium">Product Name</span>
                    </span>
                    <ChevronRightIcon className="h-5 w-5 text-muted-foreground" />
                  </p>
                </Link>
              </div>
              <div className="rounded-lg bg-muted p-4 shadow-sm">
                <Link href="#" className="group" prefetch={false}>
                  <img
                    src="/placeholder.svg"
                    alt="Product Image"
                    width={300}
                    height={300}
                    className="mb-4 h-48 w-full rounded-lg object-cover transition-opacity group-hover:opacity-80"
                    style={{ aspectRatio: "300/300", objectFit: "cover" }} />
                  <h3 className="mb-2 text-lg font-medium">Product Name</h3>
                  <p className="text-muted-foreground">$29.99</p>
                </Link>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>)
  );
}

function ChevronRightIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m9 18 6-6-6-6" />
    </svg>)
  );
}


function MenuIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>)
  );
}


function SearchIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>)
  );
}


function ShoppingBagIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M6 2 3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4Z" />
      <path d="M3 6h18" />
      <path d="M16 10a4 4 0 0 1-8 0" />
    </svg>)
  );
}


function ShoppingCartIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="8" cy="21" r="1" />
      <circle cx="19" cy="21" r="1" />
      <path
        d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" />
    </svg>)
  );
}
